services:
  - regio: ohio
  - type: web
    name: authorizer
    env: docker
    autoDeploy: false

    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: authorizer-db
          property: connectionString
      - key: DATABASE_TYPE
        value: postgres
databases:
  - name: authorizer-db
  - regio: ohio
